// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt2Wryz_70sRQXaYvAObmd-RY0M445gFo',
    appId: '1:678872102873:web:1b2b9c21a4058a28adcbc8',
    messagingSenderId: '678872102873',
    projectId: 'sos-prj',
    authDomain: 'sos-prj.firebaseapp.com',
    storageBucket: 'sos-prj.appspot.app',
    measurementId: 'G-9T5NSVGGTW',
    databaseURL: 'https://sos-prj-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvcielxcIwlol3GWMgWx1ml5yzxG1IVnk',
    appId: '1:678872102873:android:be124789245b2d89adcbc8',
    messagingSenderId: '678872102873',
    projectId: 'sos-prj',
    storageBucket: 'sos-prj.appspot.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJiugDwpANZXLV0ItltaZ6Wzwdeg3IK4',
    appId: '1:678872102873:ios:bb89d06e37a70956adcbc8',
    messagingSenderId: '678872102873',
    projectId: 'sos-prj',
    storageBucket: 'sos-prj.appspot.app',
    androidClientId: '678872102873-3eqn0ql9tpe0ab2tnrf632sgu2k69mk8.apps.googleusercontent.com',
    iosClientId: '678872102873-0il6e9pue8cfmjqu6jd2b2ujpqrn5670.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryapp.deliveryApp',
  );
}
